/**
 * enum with types for nodes
 */
export enum NodeType {
    CCIMSUser = "CCIMSUser",
    IMSUser = "IMSUser",
    GlobalPermission = "GlobalPermission",
    ProjectPermission = "ProjectPermission",
    ComponentPermission = "ComponentPermission",
    Project = "Project",
    Component = "Component",
    ComponentInterface = "ComponentInterface",
    Issue = "Issue",
    IssueComment = "IssueComment",
    DeletedIssueComment = "DeletedIssueComment",
    ReferencedByOtherEvent = "ReferencedByOtherEvent",
    ReferencedByIssueEvent = "RefenencedByIssueEvent",
    LinkEvent = "LinkEvent",
    UnlinkEvent = "UnlinkEvent",
    WasLinkedEvent = "WasLinkedEvent",
    WasUnlinkedEvent = "WasUnlinkedEvent",
    LabelledEvent = "LabelledEvent",
    UnlabelledEvent = "UnlabelledEvent",
    PinnedEvent = "PinnedEvent",
    UnpinnedEvent = "UnpinnedEvent",
    RenamedTitleEvent = "RenamedTitleEvent",
    CategoryChangedEvent = "CategoryChangedEvent",
    AssignedEvent = "AssignedEvent",
    UnassignedEvent = "UnassignedEvent",
    ClosedEvent = "ClosedEvent",
    ReopenedEvent = "ReopenedEvent",
    PriorityChangedEvent = "PriorityChangedEvent",
    StartDateChangedEvent = "StartDateChangedEvent",
    DueDateChangedEvent = "DueDateChangedEvent",
    EstimatedTimeChangedEvent = "EstimatedTimeChangedEvent",
    AddedToLocationEvent = "AddedToLocationEvent",
    RemovedFromLocationEvent = "RemovedFromLocationEvent",
    AddedToComponentEvent = "AddedToComponentEvent",
    RemovedFromComponentEvent = "RemovedFromComponentEvent",
    MarkedAsDuplicateEvent = "MarkedAsDuplicateEvent",
    UnmarkedAsDuplicateEvent = "UnmarkedAsDuplicateEvent",
    AddedArtifactEvent = "AddedArtifactEvent",
    RemovedArtifactEvent = "RemovedArtifactEvent",
    AddedNonFunctionalConstraintEvent = "AddedNonFunctionalConstraintEvent",
    RemovedNonFunctionalConstraintEvent = "RemovedNonFunctionalConstraintEvent",
    ReactionGroup = "ReactionGroup",
    Label = "Label",
    IMSSystem = "IMSSystem",
    IMSComponent = "IMSComponent",
    Body = "Body",
    Artifact = "Artifact",
    NonFunctionalConstraint = "NonFunctionalConstraint"
}